/* Install and offline status. Browser feature detection, no tracking or external calls. */
(() => {
 'use strict';
 const S=()=>window.Study;
 let installEvent=null,registration=null,ready=false,error='',checking=true;
 const file=location.protocol==='file:';
 const installed=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;if(S()?.page==='install')open();});
 window.addEventListener('appinstalled',()=>{installEvent=null;if(S()?.page==='install')open();});
 async function initialize(){
  if(file||!('serviceWorker' in navigator)||window.claude){checking=false;return;}
  try {const hadCtl=!!navigator.serviceWorker.controller,t0=Date.now();registration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!hadCtl||window.__swReloaded)return;window.__swReloaded=true;try{S()?.save?.();}catch(e){}if(Date.now()-t0<20000)location.reload();else S()?.toast?.('A new version is ready. Refresh the page to get it.');});registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&S()?.page==='install')open();});});await navigator.serviceWorker.ready;ready=true;}
  catch(e){error='Offline storage could not be prepared. Keep this page online, or use the downloaded folder.';}
  checking=false;if(S()?.page==='install')open();
 }
 function open(){S().setPage('install');const status=file?'The downloaded folder already runs offline. Open your published link on a phone to install it.':error||(!navigator.onLine&&ready?'You are offline. Your saved game is ready.':checking?'Preparing the game for offline play…':ready?'Game saved on this device for offline play.':'This browser does not support offline installation.');
  document.querySelector('#app').innerHTML=S().heading('TAKE IT WITH YOU','Your study terminal, anywhere.','Open the same published link on your phone, then add it to your home screen.')+`<div class="install-grid"><section class="panel"><h2>Install on this device</h2><div class="offline-status" role="status">${S().esc(status)}</div>${installed()?'<p class="offline-ready">Already running as an installed app.</p>':`<button class="primary" data-action="phone-install">${installEvent?'Install Study Terminal':'Show installation steps'}</button>`}${registration?.waiting?'<button data-action="phone-update">Apply available update</button>':''}<div id="install-help"><p><strong>iPhone / iPad:</strong> Open the published link in Safari. Use Share → Add to Home Screen.</p><p><strong>Android:</strong> Open the link in Chrome. Use the browser menu → Install app or Add to Home screen.</p><p><strong>Desktop:</strong> Use your browser’s install icon or app menu when available.</p></div><p class="source">Sign in to the private Site online first. Wait for the offline-ready message before disconnecting. Device or browser cleanup can remove downloaded data.</p></section><section class="panel"><h2>Bring your progress along</h2><p>Progress stays on each device. It does not automatically sync between your computer and phone.</p><ol><li>Open Progress & library on your computer and export your progress.</li><li>Transfer that JSON file to your phone.</li><li>Open the game on your phone, choose the matching player, then import the file.</li></ol><button data-action="progress">Open progress & backups</button><p class="source">Import replaces the selected player’s saved record. Export first if you want a backup. Missions, reviews, and campaign progress are included.</p>${!file?`<p>Current game link:<br><a class="install-url" href="${S().esc(location.origin+location.pathname)}">${S().esc(location.origin+location.pathname)}</a></p>`:''}</section></div>`;
 }
 const handle=(a,b)=>{if(a==='phone-install'){if(installEvent){const event=installEvent;installEvent=null;event.prompt().then(()=>event.userChoice).then(()=>{if(S().page==='install')open();}).catch(()=>S().toast('Use your browser menu to add this game to the home screen.'));}else{document.querySelector('#install-help')?.scrollIntoView({behavior:'smooth',block:'center'});S().toast(file?'Use the published game link on your phone, then follow the installation steps.':'Follow the installation steps for your device below.');}return true;}if(a==='phone-update'&&registration?.waiting){S().save();registration.waiting.postMessage({type:'ACTIVATE_UPDATE'});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});return true;}return false;};
 window.PhoneApp={open,handle,get ready(){return ready}};
 window.addEventListener('online',()=>{if(S()?.page==='install')open();});window.addEventListener('offline',()=>{if(S()?.page==='install')open();});initialize();
})();
