/* Adaptive practice, source-based coaching, missions, and campaign. */
(() => {
 'use strict';
 const S=()=>window.Study, M=()=>window.LearningModel, $=s=>document.querySelector(s), esc=v=>S().esc(v);
 const exam=()=>String(S().data.exam||window.ACTIVE_EXAM||2);
 let tickId=null;
 function state(){
  const s=S().state;
  if(!s.learning||typeof s.learning!=='object')s.learning={version:1,exams:{}};
  s.learning.exams ||= {};
  const l=s.learning.exams[exam()] ||= {items:{},events:[],campaign:{},coaching:{},mission:null};
  l.items ||= {};l.events ||= [];l.campaign ||= {};l.coaching ||= {};
  return l;
 }
 const library=kind=>kind==='mc'?S().data.questions:kind==='flash'?S().data.flashcards:S().data.math;
 const item=(kind,id)=>library(kind).find(x=>x.id===id);
 function kindFor(id){return S().data.questions.some(x=>x.id===id)?'mc':S().data.math.some(x=>x.id===id)?'math':null;}
 function observe(id,topic,correct,meta={}){
  const kind=meta.kind||kindFor(id);if(!kind)return;
  const l=state(),before=l.items[id];
  l.items[id]=M().update(before,{id,topic,kind,correct,confidence:meta.confidence||'confident',assisted:meta.assisted});
  l.events.push({id,topic,kind,correct:!!correct,at:Date.now(),assisted:!!meta.assisted,confidence:meta.confidence||'confident'});
  l.events=l.events.slice(-600);
  S().save();
 }
 function choose(kind,n,topic){return M().select(library(kind).filter(x=>!topic||x.topic===topic),state().items,n,{missed:S().state.missed,shuffle:S().shuffle});}
 function summary(topic){const pool=[...S().data.questions,...S().data.math,...S().data.flashcards].filter(x=>!topic||x.topic===topic), l=state();return {total:pool.length,due:pool.filter(x=>l.items[x.id]?.due<=Date.now()).length,seen:pool.filter(x=>l.items[x.id]).length,secure:pool.filter(x=>M().status(l.items[x.id])==='secure').length};}
 function confidenceHTML(value='unsure') {return `<fieldset class="confidence-choice"><legend>Before answering: recall or guess?</legend><button type="button" data-action="learn-confidence" data-value="confident" aria-pressed="${value==='confident'}">I know it</button><button type="button" data-action="learn-confidence" data-value="unsure" aria-pressed="${value==='unsure'}">I’m not sure</button><span>Your score is unchanged. This sets the next review.</span></fieldset>`;}
 const confidence=()=>$('.confidence-choice [aria-pressed="true"]')?.dataset.value||'confident';
 const FORMULAS={annualize:'Annual bonus = bonus × payments per year. Total compensation = base + annual bonus.',mean:'Mean = sum of pay values ÷ number of jobs.',weighted:'Weighted mean = sum of (pay × employees) ÷ total employees.',median:'Sort first. Use the middle value, or average the two middle values. Mode is the most frequent.',incumbent:'Count every employee at each pay value, then locate the middle employee position(s).',iqr:'IQR = Q3 − Q1. Fences = Q1 − 1.5 × IQR and Q3 + 1.5 × IQR.',grades:'Minimum = midpoint × (1 − range differential). Maximum = midpoint × (1 + range differential). Next midpoint = previous midpoint × (1 + midpoint differential).',points:'Pay = minimum + (midpoint − minimum) × (points above grade bottom ÷ half the grade width).',piecework:'Full sets = floor(units ÷ block size). Hourly rate = base rate + full sets × bonus. Total pay = rate × hours.','per-unit':'Base pay = units × per-unit rate. Full blocks = floor(units ÷ block size). Total = base pay + full blocks × bonus.',factors:'Factor points = degree × weight. Add the factor points.',labor:'Pay level = total compensation ÷ employees. Labor cost = pay level × employees.',compa:'Compa-ratio = pay ÷ range midpoint.',groupcompa:'Group compa-ratio = (sum of pay ÷ number of employees) ÷ midpoint. Raise to reach 1.00 = midpoint − current pay.',overtime:'Gross = 40 × rate + (hours − 40) × rate × 1.5. Then net = gross − 6.2% − 1.45% − income tax − other.',exec:'Annualize the bonus first. Total = base + bonus + LTI + benefits + perks. Component % = component ÷ total. Base at 8.7%: total = base ÷ 0.087.',workcomp:'Weekly benefit = 2/3 × weekly wage × % disability, up to the state maximum.',lease:'Agency bill = rate × hours × (1 + fee%). FUTA = 0.6% × first $7,000 per worker.',netpay:'Net pay = gross pay − Social Security − Medicare − income tax − other deductions.'};
 function checkpoints(p){
  const t=p.table;if(!t||p.origin!=='generated')return [];
  if(p.type==='mean'&&t.headers[1]==='Base pay')return [{id:'sum',label:'Sum of all pay values',answer:t.rows.reduce((n,r)=>n+Number(r[1]),0)}];
  if(p.type==='weighted'&&t.headers[1]==='Pay'&&t.headers[2]==='Employees')return [{id:'numerator',label:'Sum of pay × employees (numerator)',answer:t.rows.reduce((n,r)=>n+Number(r[1])*Number(r[2]),0)}];
  return [];
 }
 function coachState(context){const l=state();if(!l.coaching[context]){const keys=Object.keys(l.coaching);if(keys.length>=120)delete l.coaching[keys[0]];l.coaching[context]={hints:0,steps:0,checks:{},values:{},assisted:false};}return l.coaching[context];}
 function diagnostic(f,value,p){const n=window.MathEngine.parseInput(value);if(!Number.isFinite(n))return 'Enter a number first. Currency signs and commas are accepted.';if(Math.abs(n-f.answer)<=1.01)return 'Check the rounding step. '+(p.type==='points'?'Job pay rounds UP.':p.type==='piecework'?'Only complete sets count; round sets DOWN.':'Follow the rounding instruction in this problem.');if(p.type==='weighted'&&p.table?.headers[1]==='Pay'){const plain=p.table.rows.reduce((n,r)=>n+Number(r[1]),0)/p.table.rows.length;if(Math.abs(n-plain)<1.01)return 'This looks like an unweighted job average. Multiply each pay by its employee count, then divide by employees.';}return 'Recheck your setup and arithmetic. Use the source steps below to trace the calculation.';}
 function coachHTML(p,context){const c=coachState(context),extra=checkpoints(p);return `<section class="coach-panel" data-coach-context="${esc(context)}" data-problem-id="${esc(p.id)}"><div class="coach-title"><span class="mono">CALCULATION COACH</span><span>Optional help · final scoring stays separate</span></div><div class="coach-tools"><button data-action="learn-hint">${c.hints?'Hide formula hint':'Show formula hint'}</button><button data-action="learn-step">Show ${c.steps?'next ':''}source step</button></div>${c.hints?`<div class="coach-hint">${esc(FORMULAS[p.type]||'Work through the supplied source solution one step at a time.')}<small>${p.type==='grades'?'Round pay-table values normally.':p.type==='points'?'Round the job’s pay UP.':p.type==='piecework'?'Round the number of full sets DOWN.':'Use the rounding rule stated in the problem.'}</small></div>`:''}${c.steps?`<ol class="steps">${p.steps.slice(0,c.steps).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p class="source">Worked steps may reveal answers. This attempt counts as supported practice.</p>`:''}${extra.length?`<div class="coach-checkpoints">${extra.map(f=>`<label class="field">${esc(f.label)}<input type="text" inputmode="decimal" data-checkpoint="${f.id}" value="${esc(c.values[f.id]||'')}"><button data-action="learn-checkpoint" data-field="${f.id}">Check intermediate step</button><span class="coach-status" role="status">${esc(c.checks['cp-'+f.id]||'')}</span></label>`).join('')}</div>`:''}<details class="coach-detail"><summary>Check individual answers (${p.fields.length} fields)</summary><div class="coach-fields">${p.fields.map(f=>`<div><span>${esc(f.label)}</span><button data-action="learn-check-field" data-field="${esc(f.id)}">Check this field</button><span class="coach-status" role="status">${esc(c.checks[f.id]||'')}</span></div>`).join('')}</div></details><p class="source">Step checks do not award points. Submit the complete problem when you’re ready.</p></section>`;}
 let coachProblem=null;
 function getCoachProblem(){const el=$('.coach-panel');if(!el)return null;const id=el.dataset.problemId;return item('math',id)||S().state.session?.items.find(x=>x.id===id)?.problem||state().mission?.items.find(x=>x.id===id)?.problem||coachProblem;}
 function mathMeta(){const ctx=$('.coach-panel')?.dataset.coachContext;return {assisted:!!(ctx&&coachState(ctx).assisted),confidence:'confident'};}
 function renderCoach(p,context){coachProblem=p;return coachHTML(p,context);}
 function refreshCoach(){const el=$('.coach-panel'),p=getCoachProblem();if(!el||!p)return;const ctx=el.dataset.coachContext,expanded=!!el.querySelector('.coach-detail')?.open;el.outerHTML=coachHTML(p,ctx);if(expanded)$('.coach-detail').open=true;S().save();}
 function homePanel(){const n=summary(),m=state().mission;return `<section class="learning-launch"><div><span class="eyebrow">YOUR NEXT MISSION</span><h2>Make the time you have count.</h2><p>${n.due?`${n.due} items are due for a fresh recall check.`:'A focused mix of questions, recall cards, and calculations.'} ${n.secure} items have secure recall across separate days.</p></div><div class="mission-choices">${[5,10,20].map(n=>`<button data-action="learn-start" data-minutes="${n}"><strong>${n}</strong><span>MINUTES</span></button>`).join('')}</div><div class="learning-links">${m&&!m.finished?'<button class="text-button" data-action="learn-resume">Resume saved mission →</button>':''}<button class="text-button" data-action="learn-review">Review queue <span class="badge">${n.due} due</span></button><button class="text-button" data-action="mode" data-mode="campaign">Campaign map ↗</button><button class="text-button" data-action="mode" data-mode="install">Phone & offline ↗</button></div></section>`;}
 function renderSetup(){pause();S().setPage('missions');$('#app').innerHTML=S().heading('MISSION CONTROL','A little time. A clear plan.','Choose a time budget. We prioritize due reviews and mistakes, then add new material.')+homePanel()+`<div class="panel"><h2>How a mission works</h2><p>Answer a short mix of questions, flashcards, and source math. Mistakes return after a few other items. The clock is a guide, so you can finish a calculation without being cut off.</p><p>Mark a guess honestly. A correct guess comes back sooner; confident recall on separate days builds secure knowledge.</p><p class="source">5 min: up to 4 questions, 2 cards, 1 math · 10 min: 8, 4, 2 · 20 min: 16, 6, 3. Estimated time varies with the source problem and any retries.</p></div>`;}
 function queueItem(q,kind,n){return {uid:'i'+n+'-'+Date.now(),id:q.id,kind,topic:q.topic,order:kind==='mc'?S().shuffle(q.options.map((_,i)=>i)):[],...(kind==='math'?{problem:q}:{}),values:{},confidence:'unsure',revealed:false,response:null};}
 function build(minutes,topic,checkpoint=false){
  const counts=checkpoint?[6,0,0]:({5:[4,2,1],10:[8,4,2],20:[16,6,3]})[minutes]||[4,2,1];
  const mc=choose('mc',counts[0],topic),flash=choose('flash',counts[1],topic);
  const math=choose('math',counts[2],topic);const mixed=[];
  while(mc.length||flash.length||math.length){for(let i=0;i<2&&mc.length;i++)mixed.push({q:mc.shift(),kind:'mc'});if(flash.length)mixed.push({q:flash.shift(),kind:'flash'});if(mc.length)mixed.push({q:mc.shift(),kind:'mc'});if(math.length)mixed.push({q:math.shift(),kind:'math'});}
  if(!mixed.length)return S().toast('No items available for this topic.');
  const l=state();l.mission={id:'mission-'+Date.now(),minutes,topic:topic||null,checkpoint,items:mixed.map((x,i)=>queueItem(x.q,x.kind,i)),index:0,started:Date.now(),spent:0,runningSince:null,finished:false,before:summary(topic),initial:mixed.length};S().save();renderMission();
 }
 function requestStart(minutes,topic,checkpoint=false){const m=state().mission;if(m&&!m.finished){pause();S().setPage('missions');$('#app').innerHTML=S().heading('MISSION CONTROL','A mission is already saved.','Resume it or finish it early before starting another.')+`<section class="panel"><p>${m.items.filter(x=>x.response).length} / ${m.items.length} items answered.</p><div class="actions"><button class="primary" data-action="learn-resume">Resume mission</button><button data-action="learn-finish">Finish early & review</button></div></section>`;return;}build(minutes,topic,checkpoint);}
 function elapsed(m){return m.spent+(m.runningSince?Math.max(0,Date.now()-m.runningSince):0);}
 function pause(){const m=state().mission;if(m&&!m.finished&&m.runningSince){m.spent=elapsed(m);m.runningSince=null;S().save();}clearInterval(tickId);tickId=null;}
 function clock(){const m=state().mission,el=$('#mission-clock');if(!m||!el)return;const left=m.minutes*60-Math.floor(elapsed(m)/1000);if(m.runningSince&&Date.now()-m.runningSince>15000){m.spent=elapsed(m);m.runningSince=Date.now();S().save();}el.textContent=left>0?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')} left`:'Time budget reached · finish at your pace';}
 function missionProblem(it){return it.kind==='math'?it.problem:item(it.kind,it.id);}
 function renderMission(){const m=state().mission;if(!m)return renderSetup();if(m.finished)return debrief();S().setPage('missions',false);m.runningSince ||= Date.now();S().rememberActivity('mission');clearInterval(tickId);tickId=setInterval(clock,1000);const it=m.items[m.index],q=missionProblem(it);if(!q)return finish();const r=it.response;S().save();
  $('#app').innerHTML=S().heading(m.checkpoint?'CAMPAIGN / CHECKPOINT':'MISSION / ADAPTIVE PRACTICE',m.checkpoint?S().topicName(m.topic)+' checkpoint':'One step closer.','',`<span id="mission-clock" class="mission-clock"></span>`)+`<div class="session-top"><span>${it.retry?'RECALL RETRY · ':''}${it.kind==='mc'?'QUESTION':it.kind==='flash'?'RECALL CARD':'CALCULATION'} ${m.index+1} / ${m.items.length}</span><button class="text-button" data-action="learn-pause">Save & pause</button></div><div class="progressbar"><span style="width:${m.items.filter(x=>x.response).length/m.items.length*100}%"></span></div><section class="question-card"><div class="source">${esc(q.source)}</div><h2 id="mission-prompt">${esc(q.prompt||q.front)}</h2>${it.kind==='mc'?`${!r?confidenceHTML(it.confidence):''}<div class="options">${it.order.map((oi,i)=>`<button class="option ${r&&oi===q.answer?'correct':''} ${r&&r.answer===oi&&!r.correct?'incorrect':''}" data-action="learn-answer" data-answer="${oi}" ${r?'disabled':''}><span class="letter">${i+1}</span><span>${esc(q.options[oi])}</span></button>`).join('')}</div>${r?`<div class="feedback ${r.correct?'':'wrong'}" role="status"><h3>${r.correct?'Correct':'Not quite. This one will come back for practice.'}</h3><p><strong>Keyed answer:</strong> ${esc(q.options[q.answer])}</p><p>${esc(q.explanation||'The source key provides this answer without an explanation.')}</p><p class="source">${r.correct&&r.confidence==='confident'?'Scheduled for a future recall check.':'This item will return sooner.'}</p></div>`:''}`:it.kind==='flash'?`<button class="flashcard" data-action="learn-flip" ${r?'disabled':''}>${it.revealed?`<p>${esc(q.back)}</p>`:'Recall your answer, then tap to reveal.'}</button><div class="actions"><button data-action="learn-card" data-rating="again" ${!it.revealed||r?'disabled':''}>Again</button><button data-action="learn-card" data-rating="unsure" ${!it.revealed||r?'disabled':''}>Recognized it</button><button class="primary" data-action="learn-card" data-rating="got" ${!it.revealed||r?'disabled':''}>Recalled it</button></div>${r?'<p class="source" role="status">Recall rating saved. Card ratings are self-reported, separate from question accuracy.</p>':''}`:`${S().tableHTML(q.table)}${S().mathFields(q,it.values,!!r)}${r?S().mathFeedback(q):m.checkpoint?'':renderCoach(q,m.id+'-'+it.uid)}${!r?'<button class="primary" data-action="learn-grade">Check complete problem</button>':''}`}
    <div class="actions"><button data-action="learn-wrap">Finish early</button><button class="primary" data-action="learn-next" ${!r?'disabled':''}>${m.index===m.items.length-1?'See debrief':'Next →'}</button></div></section><p class="source keyboard-hint">${it.kind==='mc'?'1–4 choose an answer. ':''}Enter advances after feedback. Save & pause stops the mission clock.</p>`;clock();$('#mission-prompt').tabIndex=-1;$('#mission-prompt').focus({preventScroll:true});}
 function recordMission(result){const m=state().mission,it=m.items[m.index];if(it.response)return;it.response={...result,at:Date.now()};if(it.kind==='flash'){observe(it.id,it.topic,result.correct,{kind:'flash',confidence:result.confidence});}else S().record(it.id,it.topic,result.correct,{...result,kind:it.kind});
  if(!m.checkpoint&&(!result.correct||result.confidence==='unsure')&&!m.items.some(x=>x.id===it.id&&x.retry)){const q=missionProblem(it),retry={...queueItem(q,it.kind,m.items.length),retry:true};m.items.splice(Math.min(m.index+4,m.items.length),0,retry);}
  S().save();renderMission();}
 function finish(){const m=state().mission;if(!m||m.finished)return debrief();pause();m.finished=true;m.ended=Date.now();const original=m.items.filter(x=>!x.retry),scored=original.filter(x=>x.kind!=='flash'),correct=scored.filter(x=>x.response?.correct).length;m.result={correct,total:scored.length,answered:original.filter(x=>x.response).length};
  if(m.checkpoint){const pass=scored.length>=Math.min(6,library('mc').filter(q=>q.topic===m.topic).length)&&correct/scored.length>=.8&&m.result.answered===original.length;const c=state().campaign[m.topic] ||= {};c.lastCheckpoint={at:Date.now(),score:correct,total:scored.length,pass};if(pass)c.checkpoint=true;}
  S().state.history.unshift({mode:m.checkpoint?'checkpoint':'mission',score:correct,total:scored.length,date:new Date().toISOString()});S().state.history=S().state.history.slice(0,40);S().save();S().sound('complete');debrief();}
 function debrief(){const m=state().mission;if(!m)return renderSetup();S().setPage('missions');const original=m.items.filter(x=>!x.retry),graded=original.filter(x=>x.kind!=='flash'&&x.response),wrong=original.filter(x=>x.response&&!x.response.correct),recovered=m.items.filter(x=>x.retry&&x.response?.correct&&x.response.confidence!=='unsure'&&!x.response.assisted),unanswered=original.filter(x=>!x.response),known=original.filter(x=>x.kind==='flash'&&x.response?.confidence==='confident').length;const topics=S().data.topics.map(t=>({...t,n:wrong.filter(x=>x.topic===t.id).length})).filter(t=>t.n).sort((a,b)=>b.n-a.n).slice(0,2);const checkpoint=m.checkpoint?state().campaign[m.topic]?.lastCheckpoint:null;
  $('#app').innerHTML=S().heading('MISSION / DEBRIEF',checkpoint?(checkpoint.pass?'Checkpoint cleared.':'One more practice run.'):'Mission complete.',checkpoint?(checkpoint.pass?'Your sector boss is ready.':'Score at least 80% on all checkpoint questions to unlock the sector boss.'):'Here’s what happened, and what to do next.')+`<section class="panel debrief-grid"><div><strong>${graded.length?Math.round(graded.filter(x=>x.response.correct).length/graded.length*100)+'%':'—'}</strong><span>FIRST-TRY QUESTION / MATH ACCURACY</span></div><div><strong>${recovered.length}</strong><span>RECALLED ON A RETRY</span></div><div><strong>${known}</strong><span>CARDS SELF-RATED “RECALLED”</span></div><div><strong>${Math.max(1,Math.round(m.spent/60000))} min</strong><span>ACTIVE STUDY TIME</span></div></section><section class="panel debrief-next"><h2>${topics.length?'Give these concepts another look.':'Keep the recall going.'}</h2><p>${unanswered.length?`${unanswered.length} original items were left unanswered. `:''}${topics.length?topics.map(t=>esc(t.name)+' ('+t.n+' to revisit)').join(' · '):'Your next mission will prioritize due reviews, then broaden your coverage.'}</p><p>${recovered.length?`${recovered.length} ${recovered.length===1?'item moved':'items moved'} from a miss or guess to confident recall during this session.`:'Secure recall builds when you answer confidently again on separate days.'}</p><div class="actions"><button class="primary" data-action="learn-followup" data-topic="${esc(topics[0]?.id||'')}">Start recommended 5-minute mission →</button><button data-action="mode" data-mode="campaign">View campaign map</button><button data-action="home">Home</button></div></section><div class="section-line"><h2>YOUR NEXT REVIEW</h2></div><section class="panel"><p>${summary().due} items are due now. Misses and guesses return after about 10 minutes; confident answers return tomorrow or later.</p><button data-action="learn-review">Open review queue</button></section>${wrong.length?`<details><summary>Review ${wrong.length} original misses</summary>${wrong.map(it=>{const q=missionProblem(it);return `<article class="review-item"><div class="source">${esc(q.source)}</div><h3>${esc(q.prompt||q.front)}</h3>${it.kind==='mc'?`<p>${esc(q.options[q.answer])}</p><p>${esc(q.explanation||'')}</p>`:it.kind==='flash'?`<p>${esc(q.back)}</p>`:S().mathFeedback(q)}</article>`;}).join('')}</details>`:''}`;}
 function reviewPage(){S().setPage('review');const l=state(),all=[...S().data.questions.map(q=>({...q,kind:'mc'})),...S().data.math.map(q=>({...q,kind:'math'})),...S().data.flashcards.map(q=>({...q,kind:'flash'}))];const due=all.filter(x=>l.items[x.id]?.due<=Date.now()),soon=all.filter(x=>l.items[x.id]&&l.items[x.id].due>Date.now()).sort((a,b)=>l.items[a.id].due-l.items[b.id].due).slice(0,12);$('#app').innerHTML=S().heading('RECALL / REVIEW QUEUE','Practice that remembers.','New per-item tracking starts with this edition. Your previous missed list still helps select practice.')+`<div class="panel"><div class="stats"><div class="stat"><strong>${due.length}</strong><span>DUE NOW</span></div><div class="stat"><strong>${summary().secure}</strong><span>SECURE RECALL</span></div><div class="stat"><strong>${summary().seen}</strong><span>ITEMS TRACKED</span></div></div><p>Secure recall means at least three confident, unassisted successes across three separate days. Accuracy and guesses are tracked separately. This is a practice signal, not an exam-score prediction.</p><button class="primary" data-action="learn-start" data-minutes="5">${due.length?'Start a due-first mission':'Start adaptive practice'} →</button></div><section class="panel" style="margin-top:18px"><h2>${due.length?'Ready for review':'Coming up next'}</h2>${(due.length?due.slice(0,30):soon).map(q=>`<div class="review-queue-item"><span class="badge">${esc(q.kind)}</span><div><strong>${esc(q.prompt||q.front||q.title)}</strong><small>${esc(S().topicName(q.topic))} · ${due.length?'Due now':new Date(l.items[q.id].due).toLocaleString()} · ${l.items[q.id].correct}/${l.items[q.id].attempts} correct</small></div></div>`).join('')||'<p>No individual review history yet. Finish a mission to start your queue.</p>'}</section>`;}
 function campaign(){S().setPage('campaign');const l=state(),prefix=exam()==='3'?'e3:':'';$('#app').innerHTML=S().heading('CAMPAIGN / KNOWLEDGE SECTORS','Clear a path through the material.','Practice five different questions, pass an 80% checkpoint, then take on the sector boss.')+`<div class="campaign-map">${S().data.topics.map((t,i)=>{const attempted=library('mc').filter(q=>q.topic===t.id&&l.items[q.id]?.attempts).length,needed=Math.min(5,library('mc').filter(q=>q.topic===t.id).length),ready=attempted>=needed,c=l.campaign[t.id]||{},won=!!S().state.ops?.cleared?.[prefix+t.id],n=summary(t.id);return `<section class="sector ${won?'sector-cleared':''}"><div class="sector-heading"><span class="sector-id">${String(i+1).padStart(2,'0')}</span><div><span class="eyebrow">${won?'BOSS CLEARED':c.checkpoint?'BOSS READY':ready?'CHECKPOINT READY':'EXPLORING'}</span><h2>${esc(t.name)}</h2></div></div>${window.Fun?.storyFor?.(t.id,won)||''}<div class="sector-route"><span class="${ready?'done':''}">01 · Practice ${Math.min(attempted,needed)}/${needed}</span><span class="${c.checkpoint?'done':''}">02 · Checkpoint ${c.checkpoint?'✓':''}</span><span class="${won?'done':''}">03 · Boss ${won?'✓':''}</span></div><p>${n.seen}/${n.total} items explored · ${n.secure} secure · ${n.due} due</p>${c.lastCheckpoint?`<p class="source">Last checkpoint: ${c.lastCheckpoint.score}/${c.lastCheckpoint.total}</p>`:''}<div class="actions"><button data-action="learn-topic-practice" data-topic="${t.id}">Practice sector</button><button data-action="learn-checkpoint-start" data-topic="${t.id}" ${ready?'':'disabled'}>Checkpoint</button><button class="primary" data-action="learn-boss" data-topic="${t.id}" ${c.checkpoint||won?'':'disabled'}>${won?'Replay boss':'Challenge boss'} →</button></div></section>`;}).join('')}</div>${window.pendingHTML?.('campaign')||''}<section class="panel" style="margin-top:20px"><h2>Final archive boss</h2>${window.Fun?.storyFinal?.(!!S().state.ops?.cleared?.[prefix+'all'])||''}<p>Clear each sector boss to unlock the campaign’s final challenge. Existing boss victories still count.</p><button class="primary" data-action="learn-boss" data-topic="all" ${S().data.topics.every(t=>S().state.ops?.cleared?.[prefix+t.id])?'':'disabled'}>Challenge the archive core →</button></section><p class="source">Classic Assault remains available from Play for unrestricted practice.</p>`;}
 function enhanceResults(session){const wrong=session.items.filter(x=>!session.responses[x.id]?.correct),topics=[...new Set(wrong.map(it=>missionProblem(it)?.topic).filter(Boolean))].slice(0,2);return `<section class="panel debrief-next"><span class="eyebrow">NEXT BEST STEP</span><h2>${wrong.length?'Turn this result into your next win.':'Make it stick.'}</h2><p>${wrong.length?'Focus next on '+topics.map(t=>esc(S().topicName(t))).join(' and ')+'.':'Try a short mixed mission now, then return tomorrow to test recall again.'}</p><p class="source">${summary().due} items due now · secure recall grows across separate days.</p><button class="primary" data-action="learn-start" data-minutes="5" data-topic="${esc(topics[0]||'')}">Start recommended 5-minute mission →</button></section>`;}
 function handle(a,b){if(!a.startsWith('learn-'))return false;const l=state(),m=l.mission,it=m?.items[m.index];
  if(a==='learn-confidence'){const wrap=b.closest('.confidence-choice');wrap.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(S().page==='missions'&&it){it.confidence=b.dataset.value;S().save();}return true;}
  if(a==='learn-start'||a==='learn-followup')requestStart(+b.dataset.minutes||5,b.dataset.topic||undefined);
  else if(a==='learn-resume')renderMission();else if(a==='learn-review')reviewPage();
  else if(a==='learn-pause'){pause();S().home();}
  else if(a==='learn-wrap'){pause();$('#app').innerHTML=S().heading('MISSION / WRAP UP','Finish this mission early?','Your completed answers and recall ratings are already saved.')+'<section class="panel"><div class="actions"><button data-action="learn-resume">Keep going</button><button class="primary" data-action="learn-finish">Finish & see debrief</button></div></section>';}
  else if(a==='learn-finish')finish();
  else if(a==='learn-topic-practice')requestStart(5,b.dataset.topic);
  else if(a==='learn-checkpoint-start'){const count=library('mc').filter(q=>q.topic===b.dataset.topic&&l.items[q.id]?.attempts).length;if(count>=Math.min(5,library('mc').filter(q=>q.topic===b.dataset.topic).length))requestStart(5,b.dataset.topic,true);}
  else if(a==='learn-boss'){const prefix=exam()==='3'?'e3:':'',topic=b.dataset.topic;const ready=topic==='all'?S().data.topics.every(t=>S().state.ops?.cleared?.[prefix+t.id]):l.campaign[topic]?.checkpoint||S().state.ops?.cleared?.[prefix+topic];if(ready){S().mode('assault');document.querySelector(`[data-action="ops-start"][data-boss="${topic}"]`)?.click();}}
  else if(['learn-hint','learn-step','learn-check-field','learn-checkpoint'].includes(a)){const p=getCoachProblem(),ctx=$('.coach-panel')?.dataset.coachContext;if(!p||!ctx)return true;const c=coachState(ctx);if(a==='learn-hint'){c.hints=c.hints?0:1;c.assisted=true;}if(a==='learn-step'){c.steps=Math.min(p.steps.length,c.steps+1);c.assisted=true;}if(a==='learn-check-field'){const f=p.fields.find(x=>x.id===b.dataset.field),input=[...document.querySelectorAll('[data-math-field]')].find(x=>x.dataset.mathField===f?.id);if(f){const ok=MathEngine.checkField(f,input?.value);c.checks[f.id]=ok?'Step verified.':diagnostic(f,input?.value,p);if(!ok)c.assisted=true;}}if(a==='learn-checkpoint'){const f=checkpoints(p).find(x=>x.id===b.dataset.field);if(f){const ok=MathEngine.checkField(f,c.values[f.id]);c.checks['cp-'+f.id]=ok?'Intermediate step verified.':'Recheck the table values and arithmetic.';if(!ok)c.assisted=true;}}refreshCoach();}
  else if(!m||m.finished||!it)return true;
  else if(a==='learn-answer'&&!it.response){const q=missionProblem(it);recordMission({answer:+b.dataset.answer,correct:+b.dataset.answer===q.answer,confidence:it.confidence});}
  else if(a==='learn-flip'){it.revealed=!it.revealed;S().save();renderMission();}
  else if(a==='learn-card'&&it.revealed&&!it.response){S().state.cards[it.id]=b.dataset.rating==='got'?'got':'again';recordMission({correct:b.dataset.rating!=='again',confidence:b.dataset.rating==='got'?'confident':'unsure'});}
  else if(a==='learn-grade'&&!it.response){const p=missionProblem(it),correct=p.fields.every(f=>MathEngine.checkField(f,it.values[f.id]));recordMission({correct,confidence:'confident',...mathMeta()});}
  else if(a==='learn-next'&&it.response){if(m.index===m.items.length-1)finish();else{m.index++;S().save();renderMission();}}
  return true;
 }
 document.addEventListener('input',e=>{const target=e.target;if(target.matches('[data-checkpoint]')){const ctx=$('.coach-panel')?.dataset.coachContext;if(ctx){coachState(ctx).values[target.dataset.checkpoint]=target.value;S().save();}}if(target.matches('[data-math-field]')&&S()?.page==='missions'){const m=state().mission,it=m?.items[m.index];if(it&&!it.response){it.values[target.dataset.mathField]=target.value;S().save();}}});
 document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.repeat||e.ctrlKey||e.metaKey||e.altKey||S()?.page!=='missions'||!$('#mission-prompt')||e.target.closest('input,textarea,select,button,a,summary,[contenteditable]')||$('[aria-modal=true]')||document.body.classList.contains('nav-open'))return;const btn=/^[1-9]$/.test(e.key)?document.querySelectorAll('[data-action=learn-answer]')[Number(e.key)-1]:e.key==='Enter'?$('[data-action=learn-next]'):null;if(btn&&!btn.disabled){e.preventDefault();btn.click();}});
 window.addEventListener('pagehide',()=>{if(S())pause();});document.addEventListener('visibilitychange',()=>{if(!S())return;if(document.hidden)pause();else if(S().page==='missions'&&$('#mission-prompt')){state().mission.runningSince=Date.now();tickId=setInterval(clock,1000);}});
 window.Learning={init(){const m=state().mission;if(m)m.runningSince=null;S().save();},observe,confidenceHTML,confidence,renderCoach,mathMeta,summary,choose,homePanel,enhanceResults,handle,pause,mode(p){if(p==='missions'){renderSetup();return true;}if(p==='campaign'){campaign();return true;}if(p==='review'){reviewPage();return true;}return false;},get mission(){return state().mission},resume:renderMission,modes:[['missions','Study missions','5, 10, or 20 minutes of adaptive practice.','drill'],['campaign','Campaign map','Practice. Checkpoint. Boss.','assault'],['review','Review queue','Recall items when they are due.','flashcards']]};
})();
